
drop table ITEM cascade constraints purge;

create table ITEM (
   ITEM_ID         VARCHAR2(15) PRIMARY KEY,
   ITEM_NAME      VARCHAR2(30) NOT NULL,
   ITEM_CATEGORY      VARCHAR2(30) NOT NULL,
   ITEM_PRICE      NUMBER(20) NOT NULL,
   ITEM_CONTENT      VARCHAR2(1000) NOT NULL,
   ITEM_IMAGE      VARCHAR2(100) NOT NULL,
   ITEM_REG_DATE      DATE DEFAULT SYSDATE NOT NULL,
   ITEM_RSV_DATE      DATE DEFAULT SYSDATE NOT NULL,
   ITEM_SCORE      NUMBER(20),
   ITEM_SEX         VARCHAR2(10),
   ITEM_WEIGHT      NUMBER(10),
   ITEM_SPECIES      VARCHAR2(10)
);



