create table WISH (
   WISH_ID         VARCHAR2(15) NOT NULL PRIMARY KEY,
   WISH_ITEM_ID      VARCHAR2(15) NOT NULL REFERENCES ITEM(ITEM_ID),
   WISH_ITEM_NAME      VARCHAR2(20) NOT NULL ,
   WISH_ITEM_IMAGE      VARCHAR2(100) NOT NULL 
);